// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASMNHnQrPZ5fbkOaGMNRk7sILUCBwzEUI',
    appId: '1:781153742595:web:90f825fa7a49226df34336',
    messagingSenderId: '781153742595',
    projectId: 'instagram-clone-745cc',
    authDomain: 'instagram-clone-745cc.firebaseapp.com',
    storageBucket: 'instagram-clone-745cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2yY-tWIjz4d5nvgQM9difngv50tkS9Jo',
    appId: '1:781153742595:android:7715f14652595192f34336',
    messagingSenderId: '781153742595',
    projectId: 'instagram-clone-745cc',
    storageBucket: 'instagram-clone-745cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1TY2TMBeZJWc-mLeSpPgNtY3m0nBNQ5s',
    appId: '1:781153742595:ios:dbd726875d00a8e7f34336',
    messagingSenderId: '781153742595',
    projectId: 'instagram-clone-745cc',
    storageBucket: 'instagram-clone-745cc.appspot.com',
    iosClientId: '781153742595-mhgk1agrkas81d02tlncvv4biq1v9rte.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1TY2TMBeZJWc-mLeSpPgNtY3m0nBNQ5s',
    appId: '1:781153742595:ios:dbd726875d00a8e7f34336',
    messagingSenderId: '781153742595',
    projectId: 'instagram-clone-745cc',
    storageBucket: 'instagram-clone-745cc.appspot.com',
    iosClientId: '781153742595-mhgk1agrkas81d02tlncvv4biq1v9rte.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
